name: build test deploy
on: push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: building
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: npm i
      - run: npm run build
